# Generated by Django 4.2.9 on 2024-05-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("rollno", models.IntegerField()),
                ("marks", models.IntegerField()),
                ("gf", models.CharField(max_length=40)),
                ("bf", models.CharField(max_length=60)),
            ],
        ),
    ]
