# Generated by Django 4.2.9 on 2024-05-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eno", models.IntegerField()),
                ("ename", models.CharField(max_length=60)),
                ("esal", models.FloatField()),
                ("eadd", models.CharField(max_length=60)),
            ],
        ),
    ]
