# Generated by Django 4.2.9 on 2024-01-29 00:31

import CarDekhoApp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("description", models.CharField(max_length=90)),
                ("active", models.BooleanField(default=False)),
                (
                    "chachisnumber",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[CarDekhoApp.models.alphanumaric],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShowroomList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=60)),
                ("website", models.URLField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator,
                            django.core.validators.MinValueValidator,
                        ]
                    ),
                ),
                ("comments", models.CharField(max_length=200, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Review",
                        to="CarDekhoApp.carlist",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="carlist",
            name="showroom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="showrooms",
                to="CarDekhoApp.showroomlist",
            ),
        ),
    ]
