# Generated by Django 4.2.9 on 2024-01-21 14:37

import CarDekhoApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("description", models.CharField(max_length=90)),
                ("active", models.BooleanField(default=False)),
                (
                    "chachisnumber",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[CarDekhoApp.models.alphanumaric],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShowroomList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=60)),
                ("website", models.URLField(max_length=70)),
            ],
        ),
    ]
