# Generated by Django 4.2.9 on 2024-01-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CarDekhoApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carlist",
            name="showroom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="showrooms",
                to="CarDekhoApp.showroomlist",
            ),
        ),
    ]
